---
title: "batch rename a file based on a list"
author: "whzemuch"
date: "3/24/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE, error=FALSE  )
```

## Load packages
```{r }
library(data.table)
library(tidyverse)
library(DT)
```

### Import the raw dataframe
```{r}
file <- fread("NHASLab.txt", data.table = FALSE, header = FALSE)
colnames(file) <- c("year","description", "doc_file", "size", "date" )
datatable(file)

```
### Get the list of old files
```{r}
file_path <- list.files(".", pattern = "*.XPT", full.names = TRUE)
datatable(data.frame(files = file_path))
```

### Conctruct the dataframe with old names and new names
```{r}
names_from_to <- 
file %>% 
  mutate(xpt_file = str_replace_all(doc_file, " Doc", "")) %>% 
  mutate(
    old_file_name = paste0("./", xpt_file, ".XPT"),
    new_file_name = paste0(year, "_", xpt_file, ".XPT")
  ) %>% 
  select(old_file_name, new_file_name) %>% 
  filter(old_file_name %in% file_path) 

```


  
### Rename files
```{r}

file.rename(from = names_from_to$old_file_name, to = names_from_to$new_file_name)

file_path <- list.files(".", pattern = "*.XPT", full.names = TRUE)
datatable(data.frame(files = file_path))

```



